services:
  - type: static
    name: realestate-broker-ui
    rootDir: realestate-broker-ui
    buildCommand: npm run build
    publishPath: out
    envVars:
      - key: BACKEND_URL
        value: https://https://backend-django-2cpe.onrender.com
      - key: NEXT_STATIC_EXPORT
        value: "true"
