# Exported from Render on 2025-09-18T12:13:48Z
version: "1"
services:
- type: web
  name: yad2-mcp
  runtime: python
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: DOWNSTREAM_API_KEY
    sync: false
  - key: PYTHONUNBUFFERED
    sync: false
  - key: PLAYWRIGHT_BROWSERS_PATH
    sync: false
  - key: REDIS_URL
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m mcp.server --host 0.0.0.0 --port 8881
  healthCheckPath: /
  autoDeployTrigger: commit
  rootDir: yad2
- type: web
  name: mavat-mcp
  runtime: python
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: DOWNSTREAM_API_KEY
    sync: false
  - key: PYTHONUNBUFFERED
    sync: false
  - key: PLAYWRIGHT_BROWSERS_PATH
    sync: false
  - key: REDIS_URL
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m mcp.server --host 0.0.0.0 --port 8882
  healthCheckPath: /
  autoDeployTrigger: commit
  rootDir: mavat
- type: web
  name: govmap-mcp
  runtime: python
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: DOWNSTREAM_API_KEY
    sync: false
  - key: PYTHONUNBUFFERED
    sync: false
  - key: PLAYWRIGHT_BROWSERS_PATH
    sync: false
  - key: REDIS_URL
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m mcp.server --host 0.0.0.0 --port 8883
  healthCheckPath: /
  autoDeployTrigger: commit
  rootDir: govmap
- type: web
  name: gov-mcp
  runtime: python
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: DOWNSTREAM_API_KEY
    sync: false
  - key: PYTHONUNBUFFERED
    sync: false
  - key: PLAYWRIGHT_BROWSERS_PATH
    sync: false
  - key: REDIS_URL
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m mcp.server --host 0.0.0.0 --port 8884
  healthCheckPath: /
  autoDeployTrigger: commit
  rootDir: gov
- type: web
  name: gis-mcp
  runtime: python
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: DOWNSTREAM_API_KEY
    sync: false
  - key: PYTHONUNBUFFERED
    sync: false
  - key: PLAYWRIGHT_BROWSERS_PATH
    sync: false
  - key: REDIS_URL
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m mcp.server --host 0.0.0.0 --port 8885
  healthCheckPath: /
  autoDeployTrigger: commit
  rootDir: gis
- type: web
  name: backend-django
  runtime: docker
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: OPENAI_MODEL
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: FRONTEND_URL
    sync: false
  - key: POSTGRES_PORT
    sync: false
  - key: POSTGRES_HOST
    fromDatabase:
      name: postgres-db
      property: host
  - key: POSTGRES_PASSWORD
    fromDatabase:
      name: postgres-db
      property: password
  - key: POSTGRES_USER
    sync: false
  - key: POSTGRES_DB
    sync: false
  - key: CSRF_COOKIE_SECURE
    sync: false
  - key: SESSION_COOKIE_SECURE
    sync: false
  - key: SECURE_SSL_REDIRECT
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: GOOGLE_OAUTH_REDIRECT_URI
    sync: false
  - key: USE_POSTGRES
    sync: false
  - key: CSRF_TRUSTED_ORIGINS
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: SECURE_PROXY_SSL_HEADER
    sync: false
  - key: USE_X_FORWARDED_HOST
    sync: false
  - key: DEBUG
    sync: false
  - key: PYTHONUNBUFFERED
    sync: false
  - key: PLAYWRIGHT_BROWSERS_PATH
    sync: false
  - key: CORS_ALLOWED_ORIGINS
    sync: false
  - key: CELERY_RESULT_BACKEND
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: CELERY_BROKER_URL
    fromService:
      name: redis
      type: keyvalue
      property: connectionString
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  - key: ALLOWED_HOSTS
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  rootDir: backend-django
  previews:
    generation: manual
- type: web
  name: realestate-broker-ui
  runtime: node
  repo: https://github.com/MrAnde7son/realestate-agent
  plan: free
  envVars:
  - key: OPENAI_MODEL
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: BACKEND_URL
    sync: false
  region: oregon
  buildCommand: npm install && npm run build
  startCommand: npm run start
  domains:
  - app.nadlaner.com
  autoDeployTrigger: commit
  rootDir: realestate-broker-ui
  previews:
    generation: manual
- type: keyvalue
  name: redis
  plan: free
  region: oregon
  maxmemoryPolicy: allkeys-lru
  ipAllowList: []
databases:
- name: postgres-db
  databaseName: postgres_db_0n63
  user: postgres_db_0n63_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"
