# Generated by Django 4.2.23 on 2025-08-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('address', 'Address'), ('neighborhood', 'Neighborhood'), ('street', 'Street'), ('city', 'City'), ('parcel', 'Parcel')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('gush', models.CharField(blank=True, max_length=20, null=True)),
                ('helka', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('normalized_address', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enriching', 'Enriching'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('yad2', 'Yad2'), ('nadlan', 'Nadlan'), ('gis_permit', 'GIS Permit'), ('gis_rights', 'GIS Rights'), ('rami_plan', 'RAMI Plan'), ('tabu', 'Tabu')], max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.asset')),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['scope_type'], name='core_asset_scope_t_f7bf28_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['city'], name='core_asset_city_5da1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['neighborhood'], name='core_asset_neighbo_f30686_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['street'], name='core_asset_street_5118b9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['gush'], name='core_asset_gush_dc43e9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['helka'], name='core_asset_helka_38f908_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['normalized_address'], name='core_asset_normali_a6e301_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='core_asset_status_166994_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['asset'], name='core_source_asset_i_2e2330_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['source'], name='core_source_source_b2ad9b_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['external_id'], name='core_source_externa_22f24c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcerecord',
            unique_together={('source', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='realestatetransaction',
            index=models.Index(fields=['asset'], name='core_reales_asset_i_3b621e_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatetransaction',
            index=models.Index(fields=['deal_id'], name='core_reales_deal_id_0b6b66_idx'),
        ),
    ]
