# Generated by Django 4.2.23 on 2025-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_initial_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(default="usd", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(default="yyyy-mm-dd", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_time",
            field=models.CharField(default="09:00", max_length=5),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_urgent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=100),
        ),
    ]
