# Generated by Django 4.2.23 on 2025-08-28 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_currency_user_date_format_user_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('asset', 'Asset Report'), ('market', 'Market Report'), ('investment', 'Investment Analysis'), ('comparison', 'Property Comparison')], default='asset', max_length=50)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pages', models.IntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user'], name='core_report_user_id_d5020b_idx'), models.Index(fields=['asset'], name='core_report_asset_i_fe1a05_idx'), models.Index(fields=['report_type'], name='core_report_report__0ad0fd_idx'), models.Index(fields=['status'], name='core_report_status_4c7c3f_idx'), models.Index(fields=['generated_at'], name='core_report_generat_60c719_idx')],
            },
        ),
    ]
