# Generated by Django 4.2.23 on 2025-09-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_asset_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_number", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("file_url", models.CharField(blank=True, max_length=500)),
                ("raw", models.JSONField(default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["asset"], name="core_plan_asset_i_001fbb_idx"),
                    models.Index(
                        fields=["plan_number"], name="core_plan_plan_nu_b6c93f_idx"
                    ),
                    models.Index(fields=["status"], name="core_plan_status_75d34d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Permit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permit_number", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("file_url", models.CharField(blank=True, max_length=500)),
                ("raw", models.JSONField(default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permits",
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset"], name="core_permit_asset_i_5bbd72_idx"
                    ),
                    models.Index(
                        fields=["permit_number"], name="core_permit_permit__7a3013_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_permit_status_0ce4cd_idx"
                    ),
                ],
            },
        ),
    ]
