# Generated by Django 4.2.23 on 2025-09-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_0007_onboardingprogress_0007_plan_permit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_tokens",
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="core_sharet_token_71bc13_idx"),
                    models.Index(
                        fields=["asset"], name="core_sharet_asset_i_aac94d_idx"
                    ),
                ],
            },
        ),
    ]
