# Generated by Django 4.2.24 on 2025-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_demo_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="sections",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="report_sections",
            field=models.JSONField(default=list),
        ),
    ]
