# Generated by Django 4.2.24 on 2025-09-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_report_sections"),
        ("core", "0013_promote_admin"),
    ]

    operations = []
