# Generated by Django 4.2.24 on 2025-09-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_supportticket_consultationrequest"),
        ("core", "0014_merge_0011_report_sections_0013_promote_admin"),
    ]

    operations = []
