# Generated by Django 4.2.24 on 2025-09-08 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_asset_enrich_fields_status_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('digest_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'כללי'), ('asset', 'נכס ספציפי')], default='global', max_length=20)),
                ('trigger_type', models.CharField(choices=[('PRICE_DROP', 'ירידת מחיר'), ('NEW_LISTING', 'נכס חדש'), ('MARKET_TREND', 'שינוי בשוק'), ('DOCS_UPDATE', 'עדכון מסמכים'), ('PERMIT_STATUS', 'סטטוס היתרים'), ('NEW_GOV_TX', 'עסקה חדשה בסביבה'), ('LISTING_REMOVED', 'מודעה הוסרה')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('immediate', 'מיידי'), ('daily', 'יומי')], default='immediate', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('ppsqm', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='analyticsdaily',
            new_name='core_analyt_date_1acc3e_idx',
            old_name='core_analy_date_4b2427_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='core_analyt_created_45f7e6_idx',
            old_name='core_analy_created_1a634f_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='core_analyt_event_03ca14_idx',
            old_name='core_analy_event_8d3b50_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='core_analyt_source_48bac5_idx',
            old_name='core_analy_source_12d921_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='core_analyt_error_c_75e6c0_idx',
            old_name='core_analy_error_c_1b9f5f_idx',
        ),
        migrations.AlterField(
            model_name='analyticsdaily',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.asset'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.asset'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='alert_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.alertrule'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='core.asset'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['asset', 'created_at'], name='core_snapsh_asset_i_b47345_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['ppsqm'], name='core_snapsh_ppsqm_6e2651_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['user', 'active'], name='core_alertr_user_id_6aa9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['scope', 'asset'], name='core_alertr_scope_92be00_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['trigger_type'], name='core_alertr_trigger_cec419_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['alert_rule', 'occurred_at'], name='core_alerte_alert_r_53d37f_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['asset', 'occurred_at'], name='core_alerte_asset_i_efed6d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['payload_hash'], name='core_alerte_payload_dc2ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['delivered_at'], name='core_alerte_deliver_29bb40_idx'),
        ),
    ]
