# Generated by Django 4.2.24 on 2025-09-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alertevent_alertrule_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdaily',
            name='alert_setup_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='api_response_time_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='asset_creation_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='avg_page_load_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='bounce_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='error_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='exports_downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='filters_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='marketing_messages_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='report_generation_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='searches_performed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='session_duration_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='signup_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='unique_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('page_view_count', models.IntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0.0)),
                ('load_time', models.FloatField(default=0.0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='core.usersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='core_userse_session_5d2ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='core_userse_user_id_e1c310_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['started_at'], name='core_userse_started_cf1cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session'], name='core_pagevi_session_86ebc3_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user'], name='core_pagevi_user_id_db6a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['viewed_at'], name='core_pagevi_viewed__2bbd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_path'], name='core_pagevi_page_pa_bb83ee_idx'),
        ),
    ]
