# Generated by Django 4.2.24 on 2025-09-09 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_enhanced_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_created', models.IntegerField(default=0)),
                ('assets_updated', models.IntegerField(default=0)),
                ('contributions_made', models.IntegerField(default=0)),
                ('data_points_added', models.IntegerField(default=0)),
                ('sources_contributed', models.IntegerField(default=0)),
                ('reputation_score', models.IntegerField(default=0)),
                ('verification_count', models.IntegerField(default=0)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('show_attribution', models.BooleanField(default=True, help_text="Show attribution for this user's contributions")),
                ('public_profile', models.BooleanField(default=False, help_text="Allow other users to see this user's contribution history")),
                ('contribution_notifications', models.BooleanField(default=True, help_text='Receive notifications when others contribute to assets you created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contribution_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reputation_score'], name='core_userpr_reputat_4acfb8_idx'), models.Index(fields=['assets_created'], name='core_userpr_assets__4e5d07_idx'), models.Index(fields=['last_contribution_at'], name='core_userpr_last_co_6f7bfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('creation', 'Asset Creation'), ('enrichment', 'Data Enrichment'), ('verification', 'Data Verification'), ('update', 'Field Update'), ('source_add', 'Source Addition'), ('comment', 'Comment/Note')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Specific field that was updated (if applicable)', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (if updating existing data)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value added or updated', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the contribution (yad2, manual, etc.)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the contribution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'user'], name='core_assetc_asset_i_69deea_idx'), models.Index(fields=['contribution_type'], name='core_assetc_contrib_68529f_idx'), models.Index(fields=['created_at'], name='core_assetc_created_e35010_idx')],
            },
        ),
    ]
