# Generated by Django 4.2.24 on 2025-09-10 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_apartment_number_to_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Professional')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='ILS', max_length=3)),
                ('billing_period', models.CharField(default='monthly', max_length=20)),
                ('asset_limit', models.IntegerField(default=5)),
                ('report_limit', models.IntegerField(default=10)),
                ('alert_limit', models.IntegerField(default=5)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('data_export', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('custom_reports', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
                ('assets_used', models.IntegerField(default=0)),
                ('reports_used', models.IntegerField(default=0)),
                ('alerts_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='core.plantype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='plantype',
            index=models.Index(fields=['name'], name='core_planty_name_a74fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='plantype',
            index=models.Index(fields=['is_active'], name='core_planty_is_acti_475463_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user', 'is_active'], name='core_userpl_user_id_446756_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['expires_at'], name='core_userpl_expires_cae2be_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['stripe_subscription_id'], name='core_userpl_stripe__1abe78_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_user_plan'),
        ),
    ]
