# Generated by Django 4.2.24 on 2025-09-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_core_asset_block_dc43e9_idx_core_asset_block_531195_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Document description', null=True)),
                ('document_type', models.CharField(choices=[('permit', 'Building Permit'), ('appraisal', 'Appraisal'), ('plan', 'Planning Document'), ('contract', 'Contract'), ('deed', 'Deed'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Document status', max_length=20)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.CharField(help_text='Path to stored file', max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='External system ID (e.g., permit number)', max_length=100, null=True)),
                ('external_url', models.URLField(blank=True, help_text='URL to external document', null=True)),
                ('source', models.CharField(default='user_upload', help_text='Source of the document', max_length=100)),
                ('document_date', models.DateField(blank=True, help_text='Date the document was issued/created', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(default=dict, help_text='Additional metadata')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='asset',
            field=models.ForeignKey(help_text='Asset this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.asset'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['asset'], name='core_docume_asset_i_73216f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='core_docume_user_id_34c4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='core_docume_documen_5649ee_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='core_docume_status_daedd3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='core_docume_uploade_e13ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['external_id'], name='core_docume_externa_0b9c72_idx'),
        ),
    ]
