# Generated by Django 4.2.24 on 2025-09-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_document_model'),
        ('core', '0027_auto_20250917_1102'),
    ]

    operations = [
    ]
