# Generated by Django 4.2.24 on 2025-09-21 18:30

from django.db import migrations, models


def set_private_role(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role="member").update(role="private")


def restore_member_role(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role="private").update(role="member")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_sync_fields"),
    ]

    operations = [
        migrations.RunPython(set_private_role, restore_member_role),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("broker", "Broker"),
                    ("appraiser", "Appraiser"),
                    ("private", "Private"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]
