# Generated by Django 4.2.24 on 2025-09-28 13:07

from django.db import migrations, models


def _fetch_existing_indexes(schema_editor, table_name):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        vendor = connection.vendor

        if vendor == "sqlite":
            safe_table_name = table_name.replace("'", "''")
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='{}'".format(
                    safe_table_name
                )
            )
        elif vendor == "postgresql":
            cursor.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = current_schema() AND tablename = %s
                """,
                [table_name],
            )
        else:
            return set()

        return {row[0] for row in cursor.fetchall()}


def _drop_index_if_exists(cursor, schema_editor, name):
    cursor.execute(f"DROP INDEX IF EXISTS {schema_editor.quote_name(name)}")


def _create_index(cursor, schema_editor, name, table_name, column):
    cursor.execute(
        "CREATE INDEX {} ON {} ({})".format(
            schema_editor.quote_name(name),
            schema_editor.quote_name(table_name),
            schema_editor.quote_name(column),
        )
    )


def ensure_asset_index_names(apps, schema_editor):
    """Rename legacy asset indexes across supported database engines."""

    existing = _fetch_existing_indexes(schema_editor, "core_asset")

    mappings = [
        ("core_asset_block_dc43e9_idx", "core_asset_block_531195_idx", "block"),
        ("core_asset_parcel_38f908_idx", "core_asset_parcel_ebd705_idx", "parcel"),
        ("core_asset_subhelk_ec1101_idx", "core_asset_subparc_d57846_idx", "subparcel"),
        ("core_asset_subparcel_ec1101_idx", "core_asset_subparc_d57846_idx", "subparcel"),
    ]

    connection = schema_editor.connection

    with connection.cursor() as cursor:
        for old_name, new_name, column in mappings:
            if new_name in existing:
                continue

            if old_name in existing:
                _drop_index_if_exists(cursor, schema_editor, old_name)
            _create_index(cursor, schema_editor, new_name, "core_asset", column)
            existing.add(new_name)


def reverse_asset_index_names(apps, schema_editor):
    """Recreate the legacy asset index names when rolling back."""

    existing = _fetch_existing_indexes(schema_editor, "core_asset")

    mappings = [
        ("core_asset_block_531195_idx", "core_asset_block_dc43e9_idx", "block"),
        ("core_asset_parcel_ebd705_idx", "core_asset_parcel_38f908_idx", "parcel"),
        ("core_asset_subparc_d57846_idx", "core_asset_subhelk_ec1101_idx", "subparcel"),
    ]

    connection = schema_editor.connection

    with connection.cursor() as cursor:
        for current_name, legacy_name, column in mappings:
            if legacy_name in existing:
                continue

            if current_name in existing:
                _drop_index_if_exists(cursor, schema_editor, current_name)
            _create_index(cursor, schema_editor, legacy_name, "core_asset", column)
            existing.add(legacy_name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_permit_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_request_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_building_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_sug_bakasha_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_sw_tama_38_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_finished_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_issued_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_expiry_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_created_at_idx',
        ),
        migrations.RunPython(ensure_asset_index_names, reverse_asset_index_names),
        migrations.RemoveField(
            model_name='permit',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='building_num',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='building_stage',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='date_import',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_melel',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_nimuk',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_tosefet_achuz_shetach',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_yd_hagdala_achuz',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_yd_mevukash',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_yd_mutar',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='heara_teudat_gmar',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='k_sivug_makor',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='koteret',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='maslul_rishuy',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='ms_klali',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='ms_tik_binyan',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='oid_permit',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='open_request',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='permission_date',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='protected',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='request_num',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='request_stage',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sivug_makor',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='source',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sug_bakasha',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sw_tama_38',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sw_tama_38_chadash',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sw_tama_38_tosefet',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_1',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_2',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_3',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_4',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_5',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tochen_bakasha',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tr_hathalat_bniya',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='url_hadmaya',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='yechidot_diyur',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('tabu', 'Tabu'), ('condo_plan', 'Condominium Plan'), ('permit', 'Building Permit'), ('appraisal', 'Appraisal'), ('appraisal_decisive', 'דוח הערכה מכריע'), ('appraisal_rmi', 'RAMI Appraisal'), ('rights', 'Rights Document'), ('plan', 'Planning Document'), ('contract', 'Contract'), ('deed', 'Deed'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50),
        ),
        migrations.AlterField(
            model_name='permit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='permit',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
