# Generated by Django 4.2.24 on 2025-09-28 13:07

from django.db import connection, migrations, models


def ensure_asset_index_names(apps, schema_editor):
    """Rename legacy asset indexes in a SQLite-friendly manner.

    The project previously attempted to rename the indexes in migration 0026 by
    dropping the old names and creating new ones manually. Later on this
    migration introduced Django's native :class:`RenameIndex` operation for the
    same indexes which caused test database creation to fail because the legacy
    names were already removed. We now perform the rename manually while
    tolerating whichever naming convention currently exists.
    """

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='core_asset'"
        )
        existing = {row[0] for row in cursor.fetchall()}

    mappings = [
        ("core_asset_block_dc43e9_idx", "core_asset_block_531195_idx", "block"),
        ("core_asset_parcel_38f908_idx", "core_asset_parcel_ebd705_idx", "parcel"),
        ("core_asset_subhelk_ec1101_idx", "core_asset_subparc_d57846_idx", "subparcel"),
        ("core_asset_subparcel_ec1101_idx", "core_asset_subparc_d57846_idx", "subparcel"),
    ]

    with connection.cursor() as cursor:
        for old_name, new_name, column in mappings:
            if new_name in existing:
                continue

            if old_name in existing:
                cursor.execute(f"DROP INDEX IF EXISTS {old_name}")
            cursor.execute(f"CREATE INDEX IF NOT EXISTS {new_name} ON core_asset ({column})")
            existing.add(new_name)


def reverse_asset_index_names(apps, schema_editor):
    """Recreate the legacy asset index names when rolling back."""

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='core_asset'"
        )
        existing = {row[0] for row in cursor.fetchall()}

    mappings = [
        ("core_asset_block_531195_idx", "core_asset_block_dc43e9_idx", "block"),
        ("core_asset_parcel_ebd705_idx", "core_asset_parcel_38f908_idx", "parcel"),
        ("core_asset_subparc_d57846_idx", "core_asset_subhelk_ec1101_idx", "subparcel"),
    ]

    with connection.cursor() as cursor:
        for current_name, legacy_name, column in mappings:
            if legacy_name in existing:
                continue

            if current_name in existing:
                cursor.execute(f"DROP INDEX IF EXISTS {current_name}")
            cursor.execute(f"CREATE INDEX IF NOT EXISTS {legacy_name} ON core_asset ({column})")
            existing.add(legacy_name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_permit_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_request_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_building_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_sug_bakasha_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_sw_tama_38_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_finished_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_issued_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_expiry_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='core_permit_created_at_idx',
        ),
        migrations.RunPython(ensure_asset_index_names, reverse_asset_index_names),
        migrations.RemoveField(
            model_name='permit',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='building_num',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='building_stage',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='date_import',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_melel',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_nimuk',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_tosefet_achuz_shetach',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_yd_hagdala_achuz',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_yd_mevukash',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='hakala_yd_mutar',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='heara_teudat_gmar',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='k_sivug_makor',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='koteret',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='maslul_rishuy',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='ms_klali',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='ms_tik_binyan',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='oid_permit',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='open_request',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='permission_date',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='protected',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='request_num',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='request_stage',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sivug_makor',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='source',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sug_bakasha',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sw_tama_38',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sw_tama_38_chadash',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='sw_tama_38_tosefet',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_1',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_2',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_3',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_4',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tik_tipul_5',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tochen_bakasha',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='tr_hathalat_bniya',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='url_hadmaya',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='yechidot_diyur',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('tabu', 'Tabu'), ('condo_plan', 'Condominium Plan'), ('permit', 'Building Permit'), ('appraisal', 'Appraisal'), ('appraisal_decisive', 'דוח הערכה מכריע'), ('appraisal_rmi', 'RAMI Appraisal'), ('rights', 'Rights Document'), ('plan', 'Planning Document'), ('contract', 'Contract'), ('deed', 'Deed'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50),
        ),
        migrations.AlterField(
            model_name='permit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='permit',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
