# Generated by Django 4.2.24 on 2025-10-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_asset_market_metrics"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_block_531195_idx",
            old_name="core_asset_block_dc43e9_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_parcel_ebd705_idx",
            old_name="core_asset_parcel_38f908_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_subparc_d57846_idx",
            old_name="core_asset_subhelk_ec1101_idx",
        ),
        migrations.AddField(
            model_name="asset",
            name="avg_price_per_sqm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="max_price_per_sqm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="min_price_per_sqm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("tabu", "Tabu"),
                    ("condo_plan", "Condominium Plan"),
                    ("permit", "Building Permit"),
                    ("appraisal", "Appraisal"),
                    ("appraisal_decisive", "Decisive Appraisal"),
                    ("appraisal_rmi", "RAMI Appraisal"),
                    ("rights", "Rights Document"),
                    ("plan", "Planning Document"),
                    ("contract", "Contract"),
                    ("deed", "Deed"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of document",
                max_length=50,
            ),
        ),
    ]
