# Generated by Django 4.2.25 on 2024-09-01 00:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_add_ppm_metrics"),
    ]

    operations = []
