# Generated by Django 4.2.24 on 2025-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_add_ppm_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="block_area",
            field=models.FloatField(blank=True, help_text="שטח גוש", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="block_last_update",
            field=models.BigIntegerField(
                blank=True, help_text="תאריך עדכון אחרון גוש", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="block_registered_area",
            field=models.FloatField(blank=True, help_text="שטח גוש רשום", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="block_status",
            field=models.CharField(
                blank=True, help_text="סטטוס גוש", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="block_total_parcels",
            field=models.IntegerField(
                blank=True, help_text="מספר חלקות בגוש", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="parcel_accuracy",
            field=models.IntegerField(
                blank=True, help_text="דרגת דיוק חלקה", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="parcel_area",
            field=models.FloatField(blank=True, help_text="שטח חלקה", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="parcel_registered_area",
            field=models.FloatField(blank=True, help_text="שטח חלקה רשום", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="parcel_status",
            field=models.CharField(
                blank=True, help_text="סטטוס חלקה", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_accessible_apartments",
            field=models.IntegerField(blank=True, help_text="דירות נגישות", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_building_num",
            field=models.CharField(
                blank=True, help_text="מספר בניין", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_commercial_area",
            field=models.FloatField(blank=True, help_text="שטח מסחרי", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_construction_start_date",
            field=models.DateField(
                blank=True, help_text="תאריך התחלת בנייה", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_full_utilization",
            field=models.BooleanField(default=False, help_text="ניצול מלא"),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_housing_units",
            field=models.IntegerField(blank=True, help_text="יחידות דיור", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_mavat_plan_num",
            field=models.CharField(
                blank=True, help_text="מספר תוכנית מבאו", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_open_request_date",
            field=models.DateField(blank=True, help_text="תאריך פתיחת בקשה", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_parking_area",
            field=models.FloatField(blank=True, help_text="שטח חניה", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_parking_rooms_calculated",
            field=models.IntegerField(
                blank=True, help_text="חדרי חניה מחושבים", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_parking_units",
            field=models.IntegerField(blank=True, help_text="יחידות חניה", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_permission_num",
            field=models.CharField(
                blank=True, help_text="מספר היתר", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_process",
            field=models.CharField(
                blank=True, help_text="מסלול", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_public_area",
            field=models.FloatField(blank=True, help_text="שטח ציבורי", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_public_built_area",
            field=models.FloatField(blank=True, help_text="שטח ציבורי בנוי", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_repartition",
            field=models.BooleanField(default=False, help_text="חלוקה מחדש"),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_request_num",
            field=models.CharField(
                blank=True, help_text="מספר בקשה", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_residential_area",
            field=models.FloatField(blank=True, help_text="שטח מגורים", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_residential_units",
            field=models.IntegerField(blank=True, help_text="יחידות מגורים", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_rights_notification",
            field=models.BooleanField(default=False, help_text="הודעה על זכויות"),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_small_apartments",
            field=models.IntegerField(blank=True, help_text="דירות קטנות", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_subject_type",
            field=models.CharField(
                blank=True, help_text="סוג נושא", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_total_area",
            field=models.FloatField(blank=True, help_text="שטח כולל", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_unified_housing_area",
            field=models.FloatField(blank=True, help_text="שטח דיור מאוחד", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_unified_housing_units",
            field=models.IntegerField(
                blank=True, help_text="יחידות דיור מאוחד", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="permit_urban_renewal",
            field=models.BooleanField(default=False, help_text="חידוש עירוני"),
        ),
        migrations.AddField(
            model_name="asset",
            name="total_permits",
            field=models.IntegerField(blank=True, help_text="מספר היתרים", null=True),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["permit_status"], name="core_asset_permit__054a2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["permit_date"], name="core_asset_permit__10606c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["total_permits"], name="core_asset_total_p_41022b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["parcel_area"], name="core_asset_parcel__3de815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["block_area"], name="core_asset_block_a_5723b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["permit_housing_units"], name="core_asset_permit__8d4747_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["permit_residential_area"], name="core_asset_permit__0fa22a_idx"
            ),
        ),
    ]
