# Generated by Django 4.2.25 on 2025-10-09 08:47

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role="private").update(role="investor")
    User.objects.filter(role="member").update(role="viewer")


def backwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role="investor").update(role="private")
    User.objects.filter(role="viewer").update(role="member")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_add_gis_collector_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("broker", "Broker"),
                    ("appraiser", "Appraiser"),
                    ("investor", "Investor"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                default="investor",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.organization",
            ),
        ),
    ]
