# Generated by Django 4.2.24 on 2025-10-09 09:59

from django.db import migrations, models


def rename_indexes_if_exists(apps, schema_editor):
    """Rename legacy indexes only when they are still present."""

    connection = schema_editor.connection

    with connection.cursor() as cursor:
        vendor = connection.vendor

        if vendor == "sqlite":
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'core_asset%'"
            )
            existing_indexes = {index_name for (index_name,) in cursor.fetchall()}
        elif vendor == "postgresql":
            cursor.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = current_schema() AND tablename = %s
                """,
                ["core_asset"],
            )
            existing_indexes = {index_name for (index_name,) in cursor.fetchall()}
        else:
            existing_indexes = set()

        renames = [
            ("core_asset_block_dc43e9_idx", "core_asset_block_531195_idx", "block"),
            ("core_asset_parcel_38f908_idx", "core_asset_parcel_ebd705_idx", "parcel"),
            (
                "core_asset_subhelk_ec1101_idx",
                "core_asset_subparc_d57846_idx",
                "subparcel",
            ),
        ]

        for old_name, new_name, field_name in renames:
            if new_name in existing_indexes or old_name not in existing_indexes:
                continue

            if vendor == "postgresql":
                cursor.execute(
                    "ALTER INDEX {} RENAME TO {}".format(
                        schema_editor.quote_name(old_name),
                        schema_editor.quote_name(new_name),
                    )
                )
            elif vendor == "sqlite":
                cursor.execute(
                    "DROP INDEX {}".format(schema_editor.quote_name(old_name))
                )
                cursor.execute(
                    "CREATE INDEX {} ON {} ({})".format(
                        schema_editor.quote_name(new_name),
                        schema_editor.quote_name("core_asset"),
                        schema_editor.quote_name(field_name),
                    )
                )

            existing_indexes.discard(old_name)
            existing_indexes.add(new_name)


def reverse_rename_indexes_if_exists(apps, schema_editor):
    """Reverse the index rename when the new index exists."""

    connection = schema_editor.connection

    with connection.cursor() as cursor:
        vendor = connection.vendor

        if vendor == "sqlite":
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'core_asset%'"
            )
            existing_indexes = {index_name for (index_name,) in cursor.fetchall()}
        elif vendor == "postgresql":
            cursor.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = current_schema() AND tablename = %s
                """,
                ["core_asset"],
            )
            existing_indexes = {index_name for (index_name,) in cursor.fetchall()}
        else:
            existing_indexes = set()

        renames = [
            ("core_asset_block_531195_idx", "core_asset_block_dc43e9_idx", "block"),
            ("core_asset_parcel_ebd705_idx", "core_asset_parcel_38f908_idx", "parcel"),
            (
                "core_asset_subparc_d57846_idx",
                "core_asset_subhelk_ec1101_idx",
                "subparcel",
            ),
        ]

        for new_name, old_name, field_name in renames:
            if old_name in existing_indexes or new_name not in existing_indexes:
                continue

            if vendor == "postgresql":
                cursor.execute(
                    "ALTER INDEX {} RENAME TO {}".format(
                        schema_editor.quote_name(new_name),
                        schema_editor.quote_name(old_name),
                    )
                )
            elif vendor == "sqlite":
                cursor.execute(
                    "DROP INDEX {}".format(schema_editor.quote_name(new_name))
                )
                cursor.execute(
                    "CREATE INDEX {} ON {} ({})".format(
                        schema_editor.quote_name(old_name),
                        schema_editor.quote_name("core_asset"),
                        schema_editor.quote_name(field_name),
                    )
                )

            existing_indexes.discard(new_name)
            existing_indexes.add(old_name)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_add_gis_collector_fields"),
    ]

    operations = [
        migrations.RunPython(
            rename_indexes_if_exists, reverse_rename_indexes_if_exists
        ),
        migrations.AddField(
            model_name="asset",
            name="betterment_levy",
            field=models.CharField(
                blank=True, help_text="היטל השבחה צפוי", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="legal_restrictions",
            field=models.TextField(blank=True, help_text="מגבלות משפטיות", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="rights_usage_pct",
            field=models.FloatField(
                blank=True, help_text="רמת ניצול זכויות (%)", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="urban_renewal_potential",
            field=models.CharField(
                blank=True, help_text="פוטנציאל התחדשות", max_length=200, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["rights_usage_pct"], name="core_asset_rights__170aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["urban_renewal_potential"], name="core_asset_urban_r_5f33d7_idx"
            ),
        ),
    ]
