# Generated by Django 4.2.24 on 2025-10-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_add_gis_collector_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_block_531195_idx",
            old_name="core_asset_block_dc43e9_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_parcel_ebd705_idx",
            old_name="core_asset_parcel_38f908_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_subparc_d57846_idx",
            old_name="core_asset_subhelk_ec1101_idx",
        ),
        migrations.AddField(
            model_name="asset",
            name="betterment_levy",
            field=models.CharField(
                blank=True, help_text="היטל השבחה צפוי", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="legal_restrictions",
            field=models.TextField(blank=True, help_text="מגבלות משפטיות", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="rights_usage_pct",
            field=models.FloatField(
                blank=True, help_text="רמת ניצול זכויות (%)", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="urban_renewal_potential",
            field=models.CharField(
                blank=True, help_text="פוטנציאל התחדשות", max_length=200, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["rights_usage_pct"], name="core_asset_rights__170aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["urban_renewal_potential"], name="core_asset_urban_r_5f33d7_idx"
            ),
        ),
    ]
