# Generated by Django 4.2.24 on 2025-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_add_planning_legal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="building_coverage_pct",
            field=models.FloatField(
                blank=True, help_text="אחוז כיסוי בנייה (%)", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="height_analysis",
            field=models.JSONField(blank=True, help_text="ניתוח גובה בניין", null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="setback_analysis",
            field=models.JSONField(blank=True, help_text="ניתוח נסיגות", null=True),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["building_coverage_pct"], name="core_asset_buildin_fa4da0_idx"
            ),
        ),
    ]
