# Generated by Django 4.2.24 on 2025-10-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_add_enhanced_planning_metrics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanningMetrics",
        ),
    ]
