# Generated by Django 4.2.25 on 2025-10-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_update_document_types_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("yad2", "Yad2"),
                            ("madlan", "Madlan"),
                            ("winwin", "WinWin"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("raw", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=30),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                ("rooms", models.FloatField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="document",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="(legacy) primary asset link",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.asset",
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="(legacy) primary asset link",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permits",
                to="core.asset",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="(legacy) primary asset link",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="core.asset",
            ),
        ),
        migrations.AlterField(
            model_name="realestatetransaction",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="(legacy) primary asset link",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.asset",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("broker", "Broker"),
                    ("appraiser", "Appraiser"),
                    ("investor", "Investor"),
                    ("viewer", "Viewer"),
                    ("private", "Private"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="assets",
            field=models.ManyToManyField(
                related_name="listings_m2m",
                through="core.AssetListing",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettransaction",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettransaction",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.realestatetransaction",
            ),
        ),
        migrations.AddField(
            model_name="assetplan",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetplan",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.plan",
            ),
        ),
        migrations.AddField(
            model_name="assetpermit",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permit_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetpermit",
            name="permit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.permit",
            ),
        ),
        migrations.AddField(
            model_name="assetlisting",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetlisting",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.listing",
            ),
        ),
        migrations.AddField(
            model_name="assetdocument",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetdocument",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="assets",
            field=models.ManyToManyField(
                related_name="documents_m2m",
                through="core.AssetDocument",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="permit",
            name="assets",
            field=models.ManyToManyField(
                related_name="permits_m2m", through="core.AssetPermit", to="core.asset"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="assets",
            field=models.ManyToManyField(
                related_name="plans_m2m", through="core.AssetPlan", to="core.asset"
            ),
        ),
        migrations.AddField(
            model_name="realestatetransaction",
            name="assets",
            field=models.ManyToManyField(
                related_name="transactions_m2m",
                through="core.AssetTransaction",
                to="core.asset",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["source", "external_id"], name="core_listin_source_b3fc79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="core_listin_status_d19315_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="core_listin_price_6e330c_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["rooms"], name="core_listin_rooms_fe9357_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["area"], name="core_listin_area_edfb74_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="listing",
            unique_together={("source", "external_id")},
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(fields=["asset"], name="core_assett_asset_i_a44b39_idx"),
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["transaction"], name="core_assett_transac_aeb447_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assettransaction",
            unique_together={("transaction", "asset")},
        ),
        migrations.AddIndex(
            model_name="assetplan",
            index=models.Index(fields=["asset"], name="core_assetp_asset_i_fed230_idx"),
        ),
        migrations.AddIndex(
            model_name="assetplan",
            index=models.Index(fields=["plan"], name="core_assetp_plan_id_8ff49a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assetplan",
            unique_together={("plan", "asset")},
        ),
        migrations.AddIndex(
            model_name="assetpermit",
            index=models.Index(fields=["asset"], name="core_assetp_asset_i_20e7fd_idx"),
        ),
        migrations.AddIndex(
            model_name="assetpermit",
            index=models.Index(
                fields=["permit"], name="core_assetp_permit__00c38f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetpermit",
            unique_together={("permit", "asset")},
        ),
        migrations.AddIndex(
            model_name="assetlisting",
            index=models.Index(fields=["asset"], name="core_assetl_asset_i_b6dc96_idx"),
        ),
        migrations.AddIndex(
            model_name="assetlisting",
            index=models.Index(
                fields=["listing"], name="core_assetl_listing_a0995d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetlisting",
            unique_together={("listing", "asset")},
        ),
        migrations.AddIndex(
            model_name="assetdocument",
            index=models.Index(fields=["asset"], name="core_assetd_asset_i_dffd91_idx"),
        ),
        migrations.AddIndex(
            model_name="assetdocument",
            index=models.Index(
                fields=["document"], name="core_assetd_documen_3b78d9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetdocument",
            unique_together={("document", "asset")},
        ),
    ]
