# Generated by Django 4.2.23 on 2025-10-12 06:40
# flake8: noqa

import django.db.models.deletion

from django.db import migrations, models


def _get_existing_indexes(connection):
    """Return a set of existing index names for the ``core_asset`` table."""

    with connection.cursor() as cursor:
        vendor = connection.vendor

        if vendor == "sqlite":
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'core_asset%'"
            )
            return {index_name for (index_name,) in cursor.fetchall()}

        if vendor == "postgresql":
            cursor.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = current_schema() AND tablename = %s
                """,
                ["core_asset"],
            )
            return {index_name for (index_name,) in cursor.fetchall()}

    return set()


def rename_asset_indexes_if_present(apps, schema_editor):
    """Rename legacy indexes when they still exist in the database."""

    connection = schema_editor.connection
    existing_indexes = _get_existing_indexes(connection)

    renames = [
        ("core_asset_block_dc43e9_idx", "core_asset_block_531195_idx", "block"),
        ("core_asset_parcel_38f908_idx", "core_asset_parcel_ebd705_idx", "parcel"),
        ("core_asset_subhelk_ec1101_idx", "core_asset_subparc_d57846_idx", "subparcel"),
    ]

    with connection.cursor() as cursor:
        vendor = connection.vendor

        for old_name, new_name, field_name in renames:
            if new_name in existing_indexes or old_name not in existing_indexes:
                continue

            if vendor == "postgresql":
                cursor.execute(
                    "ALTER INDEX {} RENAME TO {}".format(
                        schema_editor.quote_name(old_name),
                        schema_editor.quote_name(new_name),
                    )
                )
            elif vendor == "sqlite":
                cursor.execute(
                    "DROP INDEX {}".format(schema_editor.quote_name(old_name))
                )
                cursor.execute(
                    "CREATE INDEX {} ON {} ({})".format(
                        schema_editor.quote_name(new_name),
                        schema_editor.quote_name("core_asset"),
                        schema_editor.quote_name(field_name),
                    )
                )

            existing_indexes.discard(old_name)
            existing_indexes.add(new_name)


def reverse_asset_index_renames_if_present(apps, schema_editor):
    """Reverse the index rename only when the new index exists."""

    connection = schema_editor.connection
    existing_indexes = _get_existing_indexes(connection)

    renames = [
        ("core_asset_block_531195_idx", "core_asset_block_dc43e9_idx", "block"),
        ("core_asset_parcel_ebd705_idx", "core_asset_parcel_38f908_idx", "parcel"),
        ("core_asset_subparc_d57846_idx", "core_asset_subhelk_ec1101_idx", "subparcel"),
    ]

    with connection.cursor() as cursor:
        vendor = connection.vendor

        for new_name, old_name, field_name in renames:
            if old_name in existing_indexes or new_name not in existing_indexes:
                continue

            if vendor == "postgresql":
                cursor.execute(
                    "ALTER INDEX {} RENAME TO {}".format(
                        schema_editor.quote_name(new_name),
                        schema_editor.quote_name(old_name),
                    )
                )
            elif vendor == "sqlite":
                cursor.execute(
                    "DROP INDEX {}".format(schema_editor.quote_name(new_name))
                )
                cursor.execute(
                    "CREATE INDEX {} ON {} ({})".format(
                        schema_editor.quote_name(old_name),
                        schema_editor.quote_name("core_asset"),
                        schema_editor.quote_name(field_name),
                    )
                )

            existing_indexes.discard(new_name)
            existing_indexes.add(old_name)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_update_document_types_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetToDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetToDecisiveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetToMavatPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetToRamiParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetToYad2Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DecisiveRecordGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decisive_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "key_fp",
                    models.CharField(
                        db_index=True,
                        help_text="Stable fingerprint from cadastral identifiers",
                        max_length=64,
                    ),
                ),
                (
                    "key_json",
                    models.JSONField(
                        default=dict, help_text="Cadastral identifiers for debugging"
                    ),
                ),
                ("appraiser", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("appraised_value", models.IntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ttl_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="TTL expiration for data refresh",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MavatPlanGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "key_fp",
                    models.CharField(
                        db_index=True,
                        help_text="Stable fingerprint from cadastral identifiers",
                        max_length=64,
                    ),
                ),
                (
                    "key_json",
                    models.JSONField(
                        default=dict, help_text="Cadastral identifiers for debugging"
                    ),
                ),
                (
                    "plan_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plan_title", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("plan_type", models.CharField(blank=True, max_length=100, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ttl_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="TTL expiration for data refresh",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RamiParcelGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rami_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "key_fp",
                    models.CharField(
                        db_index=True,
                        help_text="Stable fingerprint from cadastral identifiers",
                        max_length=64,
                    ),
                ),
                (
                    "key_json",
                    models.JSONField(
                        default=dict, help_text="Cadastral identifiers for debugging"
                    ),
                ),
                (
                    "plan_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plan_name", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("status_date", models.DateField(blank=True, null=True)),
                ("market_value", models.IntegerField(blank=True, null=True)),
                (
                    "building_rights",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ttl_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="TTL expiration for data refresh",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateTransactionGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "key_fp",
                    models.CharField(
                        db_index=True,
                        help_text="Stable fingerprint from cadastral identifiers",
                        max_length=64,
                    ),
                ),
                (
                    "key_json",
                    models.JSONField(
                        default=dict, help_text="Cadastral identifiers for debugging"
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("rooms", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ttl_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="TTL expiration for data refresh",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Yad2ListingGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "key_fp",
                    models.CharField(
                        db_index=True,
                        help_text="Stable fingerprint from cadastral identifiers",
                        max_length=64,
                    ),
                ),
                (
                    "key_json",
                    models.JSONField(
                        default=dict, help_text="Cadastral identifiers for debugging"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("rooms", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ttl_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="TTL expiration for data refresh",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            rename_asset_indexes_if_present,
            reverse_asset_index_renames_if_present,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("broker", "Broker"),
                    ("appraiser", "Appraiser"),
                    ("investor", "Investor"),
                    ("viewer", "Viewer"),
                    ("private", "Private"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="yad2listingglobal",
            index=models.Index(
                fields=["external_id"], name="core_yad2li_externa_f40029_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yad2listingglobal",
            index=models.Index(fields=["key_fp"], name="core_yad2li_key_fp_4cea67_idx"),
        ),
        migrations.AddIndex(
            model_name="yad2listingglobal",
            index=models.Index(
                fields=["ttl_expires_at"], name="core_yad2li_ttl_exp_b93591_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realestatetransactionglobal",
            index=models.Index(
                fields=["deal_id"], name="core_reales_deal_id_04bc35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realestatetransactionglobal",
            index=models.Index(fields=["key_fp"], name="core_reales_key_fp_cbc9a7_idx"),
        ),
        migrations.AddIndex(
            model_name="realestatetransactionglobal",
            index=models.Index(
                fields=["ttl_expires_at"], name="core_reales_ttl_exp_063385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ramiparcelglobal",
            index=models.Index(
                fields=["rami_id"], name="core_ramipa_rami_id_564393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ramiparcelglobal",
            index=models.Index(fields=["key_fp"], name="core_ramipa_key_fp_f99bf3_idx"),
        ),
        migrations.AddIndex(
            model_name="ramiparcelglobal",
            index=models.Index(
                fields=["ttl_expires_at"], name="core_ramipa_ttl_exp_c370ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mavatplanglobal",
            index=models.Index(
                fields=["plan_id"], name="core_mavatp_plan_id_bace6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mavatplanglobal",
            index=models.Index(fields=["key_fp"], name="core_mavatp_key_fp_272a03_idx"),
        ),
        migrations.AddIndex(
            model_name="mavatplanglobal",
            index=models.Index(
                fields=["ttl_expires_at"], name="core_mavatp_ttl_exp_d50848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisiverecordglobal",
            index=models.Index(
                fields=["decisive_id"], name="core_decisi_decisiv_1c0345_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisiverecordglobal",
            index=models.Index(fields=["key_fp"], name="core_decisi_key_fp_808a9f_idx"),
        ),
        migrations.AddIndex(
            model_name="decisiverecordglobal",
            index=models.Index(
                fields=["ttl_expires_at"], name="core_decisi_ttl_exp_246269_idx"
            ),
        ),
        migrations.AddField(
            model_name="assettoyad2listing",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yad2_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettoyad2listing",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.yad2listingglobal",
            ),
        ),
        migrations.AddField(
            model_name="assettoramiparcel",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rami_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettoramiparcel",
            name="parcel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.ramiparcelglobal",
            ),
        ),
        migrations.AddField(
            model_name="assettomavatplan",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mavat_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettomavatplan",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.mavatplanglobal",
            ),
        ),
        migrations.AddField(
            model_name="assettodecisiverecord",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisive_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettodecisiverecord",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.decisiverecordglobal",
            ),
        ),
        migrations.AddField(
            model_name="assettodeal",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_links",
                to="core.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettodeal",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_links",
                to="core.realestatetransactionglobal",
            ),
        ),
        migrations.AddIndex(
            model_name="assettoyad2listing",
            index=models.Index(fields=["asset"], name="core_assett_asset_i_b6a668_idx"),
        ),
        migrations.AddIndex(
            model_name="assettoyad2listing",
            index=models.Index(
                fields=["listing"], name="core_assett_listing_02651e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assettoyad2listing",
            unique_together={("asset", "listing")},
        ),
        migrations.AddIndex(
            model_name="assettoramiparcel",
            index=models.Index(fields=["asset"], name="core_assett_asset_i_cdcccb_idx"),
        ),
        migrations.AddIndex(
            model_name="assettoramiparcel",
            index=models.Index(
                fields=["parcel"], name="core_assett_parcel__f5316d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assettoramiparcel",
            unique_together={("asset", "parcel")},
        ),
        migrations.AddIndex(
            model_name="assettomavatplan",
            index=models.Index(fields=["asset"], name="core_assett_asset_i_f17895_idx"),
        ),
        migrations.AddIndex(
            model_name="assettomavatplan",
            index=models.Index(fields=["plan"], name="core_assett_plan_id_69af26_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assettomavatplan",
            unique_together={("asset", "plan")},
        ),
        migrations.AddIndex(
            model_name="assettodecisiverecord",
            index=models.Index(fields=["asset"], name="core_assett_asset_i_11e82d_idx"),
        ),
        migrations.AddIndex(
            model_name="assettodecisiverecord",
            index=models.Index(
                fields=["record"], name="core_assett_record__360156_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assettodecisiverecord",
            unique_together={("asset", "record")},
        ),
        migrations.AddIndex(
            model_name="assettodeal",
            index=models.Index(fields=["asset"], name="core_assett_asset_i_c135ea_idx"),
        ),
        migrations.AddIndex(
            model_name="assettodeal",
            index=models.Index(
                fields=["transaction"], name="core_assett_transac_b69cae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assettodeal",
            unique_together={("asset", "transaction")},
        ),
    ]
