# Generated by Django 4.2.23 on 2025-10-12 06:40

from django.db import migrations
from django.utils import timezone
from datetime import timedelta
import hashlib
import json


def compute_key_fingerprint(key_dict):
    """Compute a stable fingerprint from cadastral identifiers."""
    normalized = {}
    for key in sorted(key_dict.keys()):
        value = key_dict[key]
        if value is not None:
            normalized[key] = str(value).strip()
    
    key_json = json.dumps(normalized, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(key_json.encode('utf-8')).hexdigest()


def build_key_dict_from_asset(asset):
    """Build key dictionary from an Asset instance."""
    return {
        'block': asset.block,
        'parcel': asset.parcel,
        'subparcel': asset.subparcel,
        'city': asset.city,
        'street': asset.street,
        'number': asset.number,
    }


def promote_transactions_to_global(apps, schema_editor):
    """Promote existing per-asset transactions to global table."""
    RealEstateTransaction = apps.get_model('core', 'RealEstateTransaction')
    RealEstateTransactionGlobal = apps.get_model('core', 'RealEstateTransactionGlobal')
    AssetToDeal = apps.get_model('core', 'AssetToDeal')
    
    promoted_count = 0
    linked_count = 0
    
    for transaction in RealEstateTransaction.objects.all():
        try:
            # Build key dictionary from asset
            key_dict = build_key_dict_from_asset(transaction.asset)
            key_fp = compute_key_fingerprint(key_dict)
            
            # Build external ID (prefer deal_id, fallback to content hash)
            if transaction.deal_id:
                external_id = str(transaction.deal_id)
            else:
                content = {
                    'date': transaction.date.isoformat() if transaction.date else None,
                    'price': transaction.price,
                    'address': transaction.address,
                    'key_dict': key_dict,
                }
                content_json = json.dumps(content, sort_keys=True, separators=(',', ':'))
                external_id = hashlib.sha256(content_json.encode('utf-8')).hexdigest()[:32]
            
            # Create or update global transaction
            global_transaction, created = RealEstateTransactionGlobal.objects.update_or_create(
                deal_id=external_id,
                defaults={
                    'key_fp': key_fp,
                    'key_json': key_dict,
                    'date': transaction.date,
                    'price': transaction.price,
                    'rooms': transaction.rooms,
                    'area': transaction.area,
                    'floor': transaction.floor,
                    'address': transaction.address,
                    'raw': transaction.raw,
                    'ttl_expires_at': timezone.now() + timedelta(days=30),
                }
            )
            
            if created:
                promoted_count += 1
            
            # Create link
            AssetToDeal.objects.get_or_create(
                asset=transaction.asset,
                transaction=global_transaction
            )
            linked_count += 1
            
        except Exception as e:
            print(f"Error promoting transaction {transaction.id}: {e}")
    
    print(f"Promoted {promoted_count} transactions to global table")
    print(f"Created {linked_count} asset-to-deal links")


def promote_source_records_to_global(apps, schema_editor):
    """Promote existing SourceRecord data to global tables."""
    SourceRecord = apps.get_model('core', 'SourceRecord')
    MavatPlanGlobal = apps.get_model('core', 'MavatPlanGlobal')
    RamiParcelGlobal = apps.get_model('core', 'RamiParcelGlobal')
    DecisiveRecordGlobal = apps.get_model('core', 'DecisiveRecordGlobal')
    Yad2ListingGlobal = apps.get_model('core', 'Yad2ListingGlobal')
    AssetToMavatPlan = apps.get_model('core', 'AssetToMavatPlan')
    AssetToRamiParcel = apps.get_model('core', 'AssetToRamiParcel')
    AssetToDecisiveRecord = apps.get_model('core', 'AssetToDecisiveRecord')
    AssetToYad2Listing = apps.get_model('core', 'AssetToYad2Listing')
    
    promoted_counts = {'mavat': 0, 'rami': 0, 'decisive': 0, 'yad2': 0}
    linked_counts = {'mavat': 0, 'rami': 0, 'decisive': 0, 'yad2': 0}
    
    for record in SourceRecord.objects.all():
        try:
            # Build key dictionary from asset
            key_dict = build_key_dict_from_asset(record.asset)
            key_fp = compute_key_fingerprint(key_dict)
            
            if record.source == 'mavat':
                # Promote MAVAT plan
                external_id = record.external_id or hashlib.sha256(
                    json.dumps(record.raw, sort_keys=True).encode('utf-8')
                ).hexdigest()[:32]
                
                global_plan, created = MavatPlanGlobal.objects.update_or_create(
                    plan_id=external_id,
                    defaults={
                        'key_fp': key_fp,
                        'key_json': key_dict,
                        'plan_number': record.raw.get('plan_number'),
                        'plan_title': record.raw.get('plan_title'),
                        'status': record.raw.get('status'),
                        'effective_date': record.raw.get('effective_date'),
                        'plan_type': record.raw.get('plan_type'),
                        'raw': record.raw,
                        'ttl_expires_at': timezone.now() + timedelta(days=7),
                    }
                )
                
                if created:
                    promoted_counts['mavat'] += 1
                
                AssetToMavatPlan.objects.get_or_create(
                    asset=record.asset,
                    plan=global_plan
                )
                linked_counts['mavat'] += 1
                
            elif record.source in ['rami_plan', 'gov_rami']:
                # Promote RAMI parcel
                external_id = record.external_id or hashlib.sha256(
                    json.dumps(record.raw, sort_keys=True).encode('utf-8')
                ).hexdigest()[:32]
                
                global_parcel, created = RamiParcelGlobal.objects.update_or_create(
                    rami_id=external_id,
                    defaults={
                        'key_fp': key_fp,
                        'key_json': key_dict,
                        'plan_number': record.raw.get('plan_number'),
                        'plan_name': record.raw.get('plan_name'),
                        'status': record.raw.get('status'),
                        'status_date': record.raw.get('status_date'),
                        'market_value': record.raw.get('market_value'),
                        'building_rights': record.raw.get('building_rights'),
                        'raw': record.raw,
                        'ttl_expires_at': timezone.now() + timedelta(days=7),
                    }
                )
                
                if created:
                    promoted_counts['rami'] += 1
                
                AssetToRamiParcel.objects.get_or_create(
                    asset=record.asset,
                    parcel=global_parcel
                )
                linked_counts['rami'] += 1
                
            elif record.source in ['decisive', 'appraisal_decisive']:
                # Promote decisive record
                external_id = record.external_id or hashlib.sha256(
                    json.dumps(record.raw, sort_keys=True).encode('utf-8')
                ).hexdigest()[:32]
                
                global_record, created = DecisiveRecordGlobal.objects.update_or_create(
                    decisive_id=external_id,
                    defaults={
                        'key_fp': key_fp,
                        'key_json': key_dict,
                        'appraiser': record.raw.get('appraiser'),
                        'date': record.raw.get('date'),
                        'appraised_value': record.raw.get('appraised_value'),
                        'url': record.url,
                        'raw': record.raw,
                        'ttl_expires_at': timezone.now() + timedelta(days=7),
                    }
                )
                
                if created:
                    promoted_counts['decisive'] += 1
                
                AssetToDecisiveRecord.objects.get_or_create(
                    asset=record.asset,
                    record=global_record
                )
                linked_counts['decisive'] += 1
                
            elif record.source == 'yad2':
                # Promote Yad2 listing
                external_id = record.external_id or hashlib.sha256(
                    json.dumps(record.raw, sort_keys=True).encode('utf-8')
                ).hexdigest()[:32]
                
                global_listing, created = Yad2ListingGlobal.objects.update_or_create(
                    external_id=external_id,
                    defaults={
                        'key_fp': key_fp,
                        'key_json': key_dict,
                        'title': record.raw.get('title'),
                        'price': record.raw.get('price'),
                        'address': record.raw.get('address'),
                        'rooms': record.raw.get('rooms'),
                        'area': record.raw.get('area'),
                        'property_type': record.raw.get('property_type'),
                        'url': record.url,
                        'raw': record.raw,
                        'ttl_expires_at': timezone.now() + timedelta(days=1),
                    }
                )
                
                if created:
                    promoted_counts['yad2'] += 1
                
                AssetToYad2Listing.objects.get_or_create(
                    asset=record.asset,
                    listing=global_listing
                )
                linked_counts['yad2'] += 1
                
        except Exception as e:
            print(f"Error promoting source record {record.id}: {e}")
    
    for source_type, count in promoted_counts.items():
        print(f"Promoted {count} {source_type} records to global table")
    for source_type, count in linked_counts.items():
        print(f"Created {count} asset-to-{source_type} links")


def reverse_promotion(apps, schema_editor):
    """Reverse the promotion by clearing global tables."""
    RealEstateTransactionGlobal = apps.get_model('core', 'RealEstateTransactionGlobal')
    MavatPlanGlobal = apps.get_model('core', 'MavatPlanGlobal')
    RamiParcelGlobal = apps.get_model('core', 'RamiParcelGlobal')
    DecisiveRecordGlobal = apps.get_model('core', 'DecisiveRecordGlobal')
    Yad2ListingGlobal = apps.get_model('core', 'Yad2ListingGlobal')
    
    RealEstateTransactionGlobal.objects.all().delete()
    MavatPlanGlobal.objects.all().delete()
    RamiParcelGlobal.objects.all().delete()
    DecisiveRecordGlobal.objects.all().delete()
    Yad2ListingGlobal.objects.all().delete()
    
    print("Cleared all global source tables")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_global_source_tables"),
    ]

    operations = [
        migrations.RunPython(
            promote_transactions_to_global,
            reverse_promotion,
        ),
        migrations.RunPython(
            promote_source_records_to_global,
            reverse_promotion,
        ),
    ]
