# Generated by Django 4.2.25 on 2025-10-24 14:06

from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor, table_name, old_name, new_name):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
    if old_name not in constraints:
        return
    sql = schema_editor._rename_index_sql(table_name, old_name, new_name)
    schema_editor.execute(sql)


def rename_block_index(apps, schema_editor):
    rename_index_if_exists(apps, schema_editor, "core_asset", "core_asset_block_dc43e9_idx", "core_asset_block_531195_idx")


def rename_parcel_index(apps, schema_editor):
    rename_index_if_exists(apps, schema_editor, "core_asset", "core_asset_parcel_38f908_idx", "core_asset_parcel_ebd705_idx")


def rename_subparcel_index(apps, schema_editor):
    rename_index_if_exists(apps, schema_editor, "core_asset", "core_asset_subhelk_ec1101_idx", "core_asset_subparc_d57846_idx")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_add_plan_title"),
    ]

    operations = [
        migrations.RunPython(rename_block_index, migrations.RunPython.noop),
        migrations.RunPython(rename_parcel_index, migrations.RunPython.noop),
        migrations.RunPython(rename_subparcel_index, migrations.RunPython.noop),
        migrations.AddField(
            model_name="asset",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External identifier from the source system",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="external_source",
            field=models.CharField(
                blank=True,
                choices=[("nadlan_one", "Nadlan One")],
                help_text="Origin of the asset in external systems",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="import_batch_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Identifier for the bulk import batch",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["external_source", "external_id"],
                name="core_asset_externa_2109d3_idx",
            ),
        ),
    ]
