# Generated by Django 4.2.24 on 2025-10-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_add_is_commercial_to_asset"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_block_531195_idx",
            old_name="core_asset_block_dc43e9_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_parcel_ebd705_idx",
            old_name="core_asset_parcel_38f908_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_subparc_d57846_idx",
            old_name="core_asset_subhelk_ec1101_idx",
        ),
    ]
