# Generated by Django 4.2.25 on 2025-10-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_add_rent_price_to_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetWatchlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_entries",
                        to="core.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_watchlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are tracking this asset",
                related_name="watched_assets",
                through="core.AssetWatchlistEntry",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="assetwatchlistentry",
            index=models.Index(
                fields=["user", "created_at"], name="core_assetw_user_id_254451_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetwatchlistentry",
            index=models.Index(
                fields=["asset", "created_at"], name="core_assetw_asset_i_a6a3cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetwatchlistentry",
            unique_together={("user", "asset")},
        ),
    ]
