# Generated by Django 4.2.24 on 2025-11-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0054_rename_core_apitok_token_idx_core_apitok_token_8d7878_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apitoken",
            new_name="core_apitok_token_8d7878_idx",
            old_name="core_apitok_token_idx",
        ),
        migrations.RenameIndex(
            model_name="apitoken",
            new_name="core_apitok_user_id_210ba8_idx",
            old_name="core_apitok_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_block_531195_idx",
            old_name="core_asset_block_dc43e9_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_parcel_ebd705_idx",
            old_name="core_asset_parcel_38f908_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="core_asset_subparc_d57846_idx",
            old_name="core_asset_subhelk_ec1101_idx",
        ),
    ]
