# Generated by Django 4.2.24 on 2025-11-16 08:18
# Modified to use SeparateDatabaseAndState to update Django's migration state
# without actually changing the database (indexes already have correct names)

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_add_agent_chat_usage"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Don't actually change the database - indexes already have correct names
            database_operations=[],
            # Update Django's migration state to reflect current index names
            state_operations=[
                migrations.RenameIndex(
                    model_name="agentchatusage",
                    new_name="core_agentc_user_id_b8a0b3_idx",
                    old_name="core_agentc_user_idx",
                ),
                migrations.RenameIndex(
                    model_name="agentchatusage",
                    new_name="core_agentc_questio_39e242_idx",
                    old_name="core_agentc_questio_idx",
                ),
                migrations.RenameIndex(
                    model_name="apitoken",
                    new_name="core_apitok_token_8d7878_idx",
                    old_name="core_apitok_token_idx",
                ),
                migrations.RenameIndex(
                    model_name="apitoken",
                    new_name="core_apitok_user_id_210ba8_idx",
                    old_name="core_apitok_user_id_idx",
                ),
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_block_531195_idx",
                    old_name="core_asset_block_dc43e9_idx",
                ),
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_parcel_ebd705_idx",
                    old_name="core_asset_parcel_38f908_idx",
                ),
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_subparc_d57846_idx",
                    old_name="core_asset_subhelk_ec1101_idx",
                ),
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_permit__0fa22a_idx",
                    old_name="core_asset_permit__10606c_idx",
                ),
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_permit__10606c_idx",
                    old_name="core_asset_total_p_41022b_idx",
                ),
                migrations.RenameIndex(
                    model_name="oauthauthorizationcode",
                    new_name="core_oautha_code_49b93b_idx",
                    old_name="core_oauth_code_idx",
                ),
                migrations.RenameIndex(
                    model_name="oauthauthorizationcode",
                    new_name="core_oautha_client__6a2ce8_idx",
                    old_name="core_oauth_client_used_idx",
                ),
            ],
        ),
    ]
