# Generated by Django 4.2.24 on 2025-11-16 08:20
# Modified to use SeparateDatabaseAndState to update Django's migration state
# without actually changing the database (index already has correct name)

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_fix_index_names_in_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Don't actually change the database - index already has correct name
            database_operations=[],
            # Update Django's migration state to reflect current index name
            state_operations=[
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_total_p_41022b_idx",
                    old_name="core_asset_permit__0fa22a_idx",
                ),
            ],
        ),
    ]
