# Generated by Django 4.2.24 on 2025-11-16 08:20
# Modified to use SeparateDatabaseAndState - this is the final state sync
# The database already has the correct index names, we're just updating Django's state

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0066_rename_core_asset_permit__0fa22a_idx_core_asset_total_p_41022b_idx",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Don't actually change the database - index already has correct name
            database_operations=[],
            # Update Django's migration state to reflect current index name
            state_operations=[
                migrations.RenameIndex(
                    model_name="asset",
                    new_name="core_asset_permit__0fa22a_idx",
                    old_name="core_asset_total_p_41022b_idx",
                ),
            ],
        ),
    ]
