# Generated by Django 4.2.26 on 2025-11-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_add_user_monthly_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preference_area_max",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum desired asset area in square meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_area_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum desired asset area in square meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_asset_type",
            field=models.CharField(
                blank=True,
                help_text="Preferred asset type (e.g. דירה, פנטהאוז)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_city",
            field=models.CharField(
                blank=True,
                help_text="Preferred city for requested assets",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_floor",
            field=models.CharField(
                blank=True, help_text="Preferred floor or range", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the user's preferences"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_streets",
            field=models.TextField(
                blank=True,
                help_text="Preferred streets or neighbourhoods for requested assets",
            ),
        ),
    ]
