# Generated by Django 4.2.26 on 2025-12-07 07:41

from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if the old index exists and new one doesn't."""
    db_backend = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if db_backend == "sqlite":
            # Check if old index exists
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name='core_asset_permit__0fa22a_idx'
            """)
            old_exists = cursor.fetchone() is not None

            # Check if new index exists
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name='core_asset_total_p_41022b_idx'
            """)
            new_exists = cursor.fetchone() is not None

            if old_exists and not new_exists:
                # Rename the index
                cursor.execute("""
                    ALTER INDEX core_asset_permit__0fa22a_idx 
                    RENAME TO core_asset_total_p_41022b_idx
                """)
            # If new index already exists, skip (database is ahead of migration state)
            # If old index doesn't exist, skip (already renamed or never existed)
        elif db_backend == "postgresql":
            # For PostgreSQL, check pg_indexes
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename='core_asset' AND indexname='core_asset_permit__0fa22a_idx'
            """)
            old_exists = cursor.fetchone() is not None

            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename='core_asset' AND indexname='core_asset_total_p_41022b_idx'
            """)
            new_exists = cursor.fetchone() is not None

            if old_exists and not new_exists:
                cursor.execute("""
                    ALTER INDEX core_asset_permit__0fa22a_idx 
                    RENAME TO core_asset_total_p_41022b_idx
                """)


def reverse_rename_index_if_exists(apps, schema_editor):
    """Reverse rename index only if needed."""
    db_backend = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if db_backend == "sqlite":
            # Check if new index exists
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name='core_asset_total_p_41022b_idx'
            """)
            new_exists = cursor.fetchone() is not None

            # Check if old index exists
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name='core_asset_permit__0fa22a_idx'
            """)
            old_exists = cursor.fetchone() is not None

            if new_exists and not old_exists:
                # Rename back
                cursor.execute("""
                    ALTER INDEX core_asset_total_p_41022b_idx 
                    RENAME TO core_asset_permit__0fa22a_idx
                """)
        elif db_backend == "postgresql":
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename='core_asset' AND indexname='core_asset_total_p_41022b_idx'
            """)
            new_exists = cursor.fetchone() is not None

            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename='core_asset' AND indexname='core_asset_permit__0fa22a_idx'
            """)
            old_exists = cursor.fetchone() is not None

            if new_exists and not old_exists:
                cursor.execute("""
                    ALTER INDEX core_asset_total_p_41022b_idx 
                    RENAME TO core_asset_permit__0fa22a_idx
                """)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_add_user_preferences"),
    ]

    operations = [
        migrations.RunPython(
            rename_index_if_exists,
            reverse_rename_index_if_exists,
        ),
        migrations.AlterField(
            model_name="listing",
            name="source",
            field=models.CharField(
                choices=[
                    ("yad2", "Yad2"),
                    ("madlan", "Madlan"),
                    ("winwin", "WinWin"),
                    ("michrazim", "Michrazim"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcerecord",
            name="source",
            field=models.CharField(
                choices=[
                    ("yad2", "Yad2"),
                    ("nadlan", "Nadlan"),
                    ("gis_permit", "GIS Permit"),
                    ("gis_rights", "GIS Rights"),
                    ("rami_plan", "RAMI Plan"),
                    ("michrazim", "Michrazim"),
                    ("tabu", "Tabu"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["created_at", "id"], name="core_asset_created_1e4aaf_idx"
            ),
        ),
    ]
