# Generated by Django 4.2.27 on 2025-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0070_rename_core_asset_permit__0fa22a_idx_core_asset_total_p_41022b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assettransaction",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.UniqueConstraint(
                fields=("transaction", "asset"), name="unique_transaction_asset_link"
            ),
        ),
    ]
