# Generated by Django 4.2.25 on 2025-10-28 17:48
# flake8: noqa

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0050_add_rent_price_to_asset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("negotiation", "Negotiation"),
                            ("legal", "Legal"),
                            ("financing", "Financing"),
                            ("closing", "Closing"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("restricted", "Restricted"),
                            ("internal", "Internal"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="core.asset",
                    ),
                ),
                (
                    "deal_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("appraisal", "Appraisal"),
                            ("architect", "Architect"),
                            ("mortgage", "Mortgage"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("storage_url", models.URLField(max_length=500)),
                ("hash", models.CharField(blank=True, max_length=128)),
                (
                    "visibility_scope",
                    models.CharField(
                        choices=[
                            ("deal", "Entire Deal"),
                            ("buyer_side", "Buyer Side"),
                            ("seller_side", "Seller Side"),
                            ("public_link", "Public Link"),
                        ],
                        default="deal",
                        max_length=20,
                    ),
                ),
                ("extracted_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_documents",
                        to="core.asset",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="deal_workspace.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortgageApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_bank", "Pending Bank"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                (
                    "ltv_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("income_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Negotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "visibility_rules",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                ("currency", models.CharField(default="ILS", max_length=8)),
                (
                    "financing_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mortgage", "Mortgage"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "down_payment_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "conditions_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("expiration_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("countered", "Countered"),
                            ("accepted", "Accepted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="deal_workspace.negotiation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartyRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_contact_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("agent", "Agent"),
                            ("lawyer", "Lawyer"),
                            ("architect", "Architect"),
                            ("banker", "Banker"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_roles",
                        to="deal_workspace.deal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="party_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "architect_partyrole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_sets",
                        to="deal_workspace.partyrole",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_sets",
                        to="core.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_attachments",
                        to="deal_workspace.document",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="deal_workspace.offer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="offer",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers_submitted",
                to="deal_workspace.partyrole",
            ),
        ),
        migrations.AddField(
            model_name="negotiation",
            name="current_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_negotiations",
                to="deal_workspace.offer",
            ),
        ),
        migrations.AddField(
            model_name="negotiation",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="deal_workspace.deal",
            ),
        ),
        migrations.CreateModel(
            name="MortgageOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lender_name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("variable", "Variable"),
                            ("mixed", "Mixed"),
                            ("prime", "Prime"),
                            ("linked_cpi", "Linked CPI"),
                            ("non_linked", "Non Linked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("term_months", models.PositiveIntegerField()),
                (
                    "rate_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "apr_estimate_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fees_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("valid_until", models.DateTimeField()),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=20)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mortgageapplication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="deal_workspace.mortgageapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mortgageapplication",
            name="applicant_partyrole",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mortgage_applications",
                to="deal_workspace.partyrole",
            ),
        ),
        migrations.AddField(
            model_name="mortgageapplication",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mortgage_applications",
                to="deal_workspace.deal",
            ),
        ),
        migrations.CreateModel(
            name="LegalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("awaiting_docs", "Awaiting Documents"),
                            ("review", "Review"),
                            ("signed", "Signed"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_cases",
                        to="deal_workspace.deal",
                    ),
                ),
                (
                    "responsible_partyrole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_cases",
                        to="deal_workspace.partyrole",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="uploader_partyrole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="deal_workspace.partyrole",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("diff_json", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ua", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "by_partyrole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="deal_workspace.partyrole",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appraised_value",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                ("valuation_date", models.DateField()),
                ("appraiser_name", models.CharField(max_length=255)),
                ("methodology", models.CharField(blank=True, max_length=255)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("external_api", "External API"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "variance_vs_nadlaner_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisals",
                        to="core.asset",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appraisals",
                        to="deal_workspace.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("checklist_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee_partyrole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="deal_workspace.partyrole",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="deal_workspace.deal",
                    ),
                ),
                (
                    "legalcase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="deal_workspace.legalcase",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["due_at", "status"],
                        name="deal_worksp_due_at_9c1912_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="partyrole",
            index=models.Index(
                fields=["deal", "role"], name="deal_worksp_deal_id_971929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partyrole",
            index=models.Index(
                fields=["deal", "side"], name="deal_worksp_deal_id_5c04a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["expiration_at", "status"],
                name="deal_worksp_expirat_d47bdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["deal", "status"],
                name="deal_worksp_deal_id_793ece_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mortgageoffer",
            index=models.Index(
                fields=["valid_until", "score"],
                name="deal_worksp_valid_u_c73590_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["kind", "status"], name="deal_worksp_kind_44799e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["deal", "visibility_scope"],
                name="deal_worksp_deal_id_ff25a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["asset", "stage"],
                name="deal_worksp_asset_i_3270ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["deal_lead"], name="deal_worksp_deal_le_14d942_idx"
            ),
        ),
    ]
