# Generated by Django 4.2.24 on 2025-09-19 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_add_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact full name', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags like ['משקיע', 'VIP']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('negotiating', 'Negotiating'), ('closed-won', 'Closed Won'), ('closed-lost', 'Closed Lost')], default='new', max_length=32)),
                ('notes', models.JSONField(blank=True, default=list, help_text="List of notes: [{'ts': ISO, 'text': '...'}]")),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.asset')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'last_activity_at'], name='crm_lead_status_c94eee_idx'), models.Index(fields=['contact', 'asset'], name='crm_lead_contact_eeb780_idx')],
                'unique_together': {('contact', 'asset')},
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'name'], name='crm_contact_owner_i_bac9ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('owner', 'email'), name='unique_owner_email'),
        ),
    ]
