# Generated by Django 4.2.24 on 2025-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_contact_crm_contact_name_e9345e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="equity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional equity amount to support mortgage insights",
                max_digits=12,
                null=True,
            ),
        ),
    ]
