# Generated by Django 4.2.24 on 2025-09-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contacttask_contactmeeting_contactinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttask',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Optional lead this task is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead'),
        ),
        migrations.AddIndex(
            model_name='contacttask',
            index=models.Index(fields=['lead', 'status'], name='crm_contact_lead_id_95f28d_idx'),
        ),
    ]
