# Generated by Django 4.2.24 on 2025-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_contacttask_lead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="area_max",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum desired asset area in square meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="area_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum desired asset area in square meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="asset_type",
            field=models.CharField(
                blank=True,
                help_text="Preferred asset type (e.g. דירה, פנטהאוז)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Preferred city for requested assets",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="floor",
            field=models.CharField(
                blank=True, help_text="Preferred floor or range", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the client's preferences"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="streets",
            field=models.TextField(
                blank=True,
                help_text="Preferred streets or neighbourhoods for requested assets",
            ),
        ),
    ]
