# Generated by Django 4.2.25 on 2025-10-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_contact_area_max_contact_area_min_contact_asset_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External system primary key",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="external_source",
            field=models.CharField(
                blank=True,
                choices=[("nadlan_one", "Nadlan One")],
                help_text="External system source identifier",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="import_batch_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Batch identifier used during bulk import",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["external_source", "external_id"],
                name="crm_contact_externa_903049_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("external_source__isnull", False),
                    models.Q(("external_source", ""), _negated=True),
                    ("external_id__isnull", False),
                    models.Q(("external_id", ""), _negated=True),
                ),
                fields=("external_source", "external_id"),
                name="unique_contact_external_id",
            ),
        ),
    ]
