# Generated by Django 4.2.25 on 2025-10-28 19:35

from django.db import migrations, models


def add_lead_task_columns(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in introspection.get_table_description(cursor, "crm_lead")
        }

        if "completed_tasks_count" not in existing_columns:
            cursor.execute(
                "ALTER TABLE crm_lead ADD COLUMN completed_tasks_count INTEGER NOT NULL DEFAULT 0"
            )
        if "pending_tasks_count" not in existing_columns:
            cursor.execute(
                "ALTER TABLE crm_lead ADD COLUMN pending_tasks_count INTEGER NOT NULL DEFAULT 0"
            )
        if "total_tasks_count" not in existing_columns:
            cursor.execute(
                "ALTER TABLE crm_lead ADD COLUMN total_tasks_count INTEGER NOT NULL DEFAULT 0"
            )


def remove_lead_task_columns(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in introspection.get_table_description(cursor, "crm_lead")
        }

        for column in (
            "completed_tasks_count",
            "pending_tasks_count",
            "total_tasks_count",
        ):
            if column in existing_columns:
                cursor.execute(f"ALTER TABLE crm_lead DROP COLUMN {column}")


def recompute_total_tasks(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    Lead.objects.all().update(
        total_tasks_count=models.F("completed_tasks_count")
        + models.F("pending_tasks_count")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0007_contact_external_id_contact_external_source_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_lead_task_columns, remove_lead_task_columns),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="lead",
                    name="completed_tasks_count",
                    field=models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of associated contact tasks marked as completed",
                    ),
                ),
                migrations.AddField(
                    model_name="lead",
                    name="pending_tasks_count",
                    field=models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of associated contact tasks still pending",
                    ),
                ),
                migrations.AddField(
                    model_name="lead",
                    name="total_tasks_count",
                    field=models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Total number of contact tasks linked to this lead",
                    ),
                ),
            ],
        ),
        migrations.RunPython(recompute_total_tasks, migrations.RunPython.noop),
    ]
