# Generated by Django 4.2.25 on 2025-10-24 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("mode", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("totals", models.JSONField(default=dict)),
                ("dry_run", models.BooleanField(default=False)),
                ("conflict_policy", models.CharField(default="update", max_length=20)),
                ("enable_linking", models.BooleanField(default=False)),
                (
                    "customers_csv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=imports.models._source_upload_path,
                    ),
                ),
                (
                    "properties_csv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=imports.models._source_upload_path,
                    ),
                ),
                (
                    "report_csv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=imports.models._report_upload_path,
                    ),
                ),
                (
                    "report_json",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=imports.models._report_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "mode"], name="imports_imp_source_97f7b5_idx"
                    ),
                    models.Index(
                        fields=["status"], name="imports_imp_status_22f3a0_idx"
                    ),
                    models.Index(
                        fields=["user"], name="imports_imp_user_id_d5f66e_idx"
                    ),
                ],
            },
        ),
    ]
