name: Block Direct Pushes

on:
  push:
    branches: [ main ]

jobs:
  block-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct pushes to main
        run: |
          if [ "${{ github.actor }}" != "web-flow" ]; then
            echo "Direct pushes to main are not allowed. Use feature branches and pull requests."
            exit 1
          else
            echo "Merge commit detected."
          fi
