name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            python:
              - 'gov/**'
              - 'gis/**'
              - 'yad2/**'
              - 'tests/**'
            broker_ui:
              - 'realestate-broker-ui/**'

      - name: Set up Python
        if: steps.changes.outputs.python == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: steps.changes.outputs.python == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Python tests
        if: steps.changes.outputs.python == 'true'
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q

      - name: Set up Node
        if: steps.changes.outputs.broker_ui == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install UI dependencies
        if: steps.changes.outputs.broker_ui == 'true'
        working-directory: realestate-broker-ui
        run: |
          npm install

      - name: Run UI tests
        if: steps.changes.outputs.broker_ui == 'true'
        working-directory: realestate-broker-ui
        run: |
          npm test --if-present
